### ISSUE TITLE
[Question] patches in aosp-10 4.9 kernel build

### ISSUE THREAD

**Issue by chris42** [stefanhh0/aosp-10#3]
@stefanhh0 
Tried your script for kugo, as it seems that it will take a while before Sony gets to that device and have it running on 10.
It seems to work, even though GApps is messing around, but will remove it either way.

My question is regarding the patches and reverts you are applying, like screen, LED, etc. Why are you doing this? Is this due to errors you encounter, specifics for your platform? Just would like to understand.

Thanks
  Chris

**Comment by stefanhh0** [comment]
Hello Chris,

happy that it basically works for you. What is wrong with the gapps? I only get one error message https://github.com/opengapps/opengapps-app-support/issues/141 but besides that everything works fine.

Regarding the commit revert https://github.com/sonyxperiadev/device-sony-common/pull/658
It is kernel 4.14 specific change therefore I don't think it will work for 4.9. However I never tried what happens.

Best regards
Stefan

**Comment by chris42** [comment]
When booting up, gapps gets stuck in an endless config run. But it doesn't matter, I am not using gapps on my phone, so I just removed it.

Yes, the LED stuff is "useless", the revert isn't working on loire platform. Hence I removed that as well.
I guess the rest of the reverts/patches is for android-10/kernel-4.9 adaptations, as they are not within the 4.14 build script? 
So far I got no errors with them and it is compiling.

**Comment by stefanhh0** [comment]
> When booting up, gapps gets stuck in an endless config run.

Just some thoughts on that:

- I had such a behavior in the past with opengapps. When rebooting it another time it worked then just fine for me. However it might be something different. 
- An option would be to check if it makes a difference when using a vanilla user.img from the very same built (in case you haven't done it anyway).
- I have removed the `GooglePermissionController` since to me that seems not to be required, however it may change something in your context. See as well the chat with Marijn: https://github.com/MarijnS95/opengapps_aosp_build/commit/b21b4598f0f654e5da098c43436ea905288836e7#commitcomment-36531279

> Yes, the LED stuff is "useless", the revert isn't working on loire platform. Hence I removed that as well.

I see, why did the revert fail for you? Reverting the commit should not be platform/device depending. Maybe there is missing something in the script that could be improved?

> I guess the rest of the reverts/patches is for android-10/kernel-4.9 adaptations, as they are not within the 4.14 build script?

Correct!

**Comment by chris42** [comment]
> I see, why did the revert fail for you? Reverting the commit should not be platform/device depending. Maybe there is missing something in the script that could be improved?

The search in the git log produces nothing within the loire platform directory. I guess the change was lilac specific.
Hence the `git revert --no-edit` fails, as no other arguments are given and the script stops.

Will let you know how the current compile turns out (It takes a while as it is not yet picking up ccache correctly).
Thanks so far for your work to get a running build!

**Comment by stefanhh0** [comment]
> The search in the git log produces nothing within the loire platform directory. I guess the change was lilac specific.
> Hence the git revert --no-edit fails, as no other arguments are given and the script stops.

Thanks for reporting it, I've fixed it and made it conditionally: https://github.com/stefanhh0/aosp-10/commit/ada51b497d7b358dcdea4b07c71dbbd6fdca78e2

**Comment by chris42** [comment]
So I did a new compile without opengapps, it works pretty much like Android 9, so thank you for doing all that backwards compatibility work!
Sadly, as it works like Android 9, all my errors from there are still existent and I have to wait for Sony to fix them. :-/
At least I can do some testing for Android 10 in other projects.
Will close this issue then.
